### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by BrooksColeold** [dcadata/predictit-arbitrage#2]
I am getting an invalid syntax error on line 158

  File "task.py", line 158
    if arbs_count := _calculate():
                   ^
SyntaxError: invalid syntax

**Comment by dcadata** [comment]
Use Python 3.10 https://github.com/dcadata/predictit-arbitrage/blob/main/.github/workflows/task.yml#L15

Or any other Python version that allows a walrus operator: https://realpython.com/python-walrus-operator/

**Comment by BrooksColeold** [comment]
Got it running, thank you!
